name: giro_certo
description: Comunidade para motociclistas com controlo de manutenção e ranking de peças
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  lucide_icons: ^0.257.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.1.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  path: ^1.8.3
  cached_network_image: ^3.3.1
  socket_io_client: ^2.0.3+1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/marca/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon.png"
